-- Transactional network installer for the from-scratch FOG Exotic automation.
-- The public release is expected at the immutable tag below.

local component = require("component")
local filesystem = require("filesystem")
local internet = require("internet")
local shell = require("shell")

local releaseTag = "exotic-iohub-v10"
local baseUrl = "https://raw.githubusercontent.com/Dragonators/OC_Scripts/"
  .. releaseTag .. "/src/ExoticIOHub/"
local targetRoot = shell.resolve((...) or "/home")
local stageRoot = filesystem.concat(targetRoot, ".fog-exotic-install-stage")
local rollbackRoot = filesystem.concat(targetRoot, ".fog-exotic-install-rollback")
local rollbackMarker = filesystem.concat(rollbackRoot, "ACTIVE")

local function wrapper(configName)
  local programPath = filesystem.concat(targetRoot, "fog_exotic.lua")
  local configPath = filesystem.concat(targetRoot, configName)
  return table.concat({
    "-- Generated by the FOG Exotic installer.",
    "local program, reason = loadfile(" .. string.format("%q", programPath) .. ")",
    "if not program then error(\"无法载入新版 FOG 自动化：\" .. tostring(reason), 0) end",
    "return program(" .. string.format("%q", configPath) .. ")",
    "",
  }, "\n")
end

local files = {
  {source = "fog_exotic.lua", target = "fog_exotic.lua", lua = true},
  {source = "fog_quark.cfg", target = "fog_quark.cfg", configMode = "quark", preserve = true},
  {source = "fog_magmatter.cfg", target = "fog_magmatter.cfg", configMode = "magmatter", preserve = true},
  {target = "quark.lua", generated = function() return wrapper("fog_quark.cfg") end, lua = true},
  {target = "magmatter.lua", generated = function() return wrapper("fog_magmatter.cfg") end, lua = true},
  {source = "README.md", target = "FOG_EXOTIC.md"},
  {source = "install.lua", target = "fog_exotic_install.lua", lua = true},
}

local function ensureDirectory(path)
  if filesystem.exists(path) then
    if not filesystem.isDirectory(path) then error(path .. " 已存在但不是目录", 0) end
    return
  end
  local ok, reason = filesystem.makeDirectory(path)
  if not ok then error("无法创建目录 " .. path .. "：" .. tostring(reason), 0) end
end

local function removeTree(path)
  if not filesystem.exists(path) then return end
  if filesystem.isDirectory(path) then
    local iterator, reason = filesystem.list(path)
    if not iterator then error("无法读取目录 " .. path .. "：" .. tostring(reason), 0) end
    for name in iterator do removeTree(filesystem.concat(path, name)) end
  end
  local ok, reason = filesystem.remove(path)
  if not ok then error("无法删除 " .. path .. "：" .. tostring(reason), 0) end
end

local function finishOutput(file, path)
  local flushed, flushError = file:flush()
  if not flushed then
    pcall(function() file:close() end)
    error("刷新 " .. path .. " 失败：" .. tostring(flushError), 0)
  end
  local closed, closeError = pcall(function() file:close() end)
  if not closed then error("关闭 " .. path .. " 失败：" .. tostring(closeError), 0) end
end

local function writeChecked(path, content)
  local output, reason = io.open(path, "wb")
  if not output then error("无法写入 " .. path .. "：" .. tostring(reason), 0) end
  local ok, writeError = pcall(function()
    local written, detail = output:write(content)
    if not written then error(detail or "unknown write error", 0) end
    finishOutput(output, path)
    output = nil
  end)
  if output then pcall(function() output:close() end) end
  if not ok then
    pcall(filesystem.remove, path)
    error("写入 " .. path .. " 失败：" .. tostring(writeError), 0)
  end
end

local function copyChecked(sourcePath, targetPath)
  local input, inputError = io.open(sourcePath, "rb")
  if not input then error("无法读取 " .. sourcePath .. "：" .. tostring(inputError), 0) end
  local output, outputError = io.open(targetPath, "wb")
  if not output then
    input:close()
    error("无法写入 " .. targetPath .. "：" .. tostring(outputError), 0)
  end

  local ok, copyError = pcall(function()
    while true do
      local chunk, readError = input:read(8192)
      if chunk == nil then
        if readError then error(readError, 0) end
        break
      end
      local written, writeError = output:write(chunk)
      if not written then error(writeError or "unknown write error", 0) end
    end
    finishOutput(output, targetPath)
    output = nil
    input:close()
    input = nil
  end)

  if output then pcall(function() output:close() end) end
  if input then pcall(function() input:close() end) end
  if not ok then
    pcall(filesystem.remove, targetPath)
    error("复制 " .. sourcePath .. " 失败：" .. tostring(copyError), 0)
  end
end

local function download(relativePath, targetPath)
  local tempPath = targetPath .. ".download"
  if filesystem.exists(tempPath) then removeTree(tempPath) end

  local requestOK, response, requestReason = pcall(internet.request, baseUrl .. relativePath)
  if not requestOK then error("下载 " .. relativePath .. " 失败：" .. tostring(response), 0) end
  if not response then error("下载 " .. relativePath .. " 失败：" .. tostring(requestReason), 0) end

  local output, openError = io.open(tempPath, "wb")
  if not output then error("无法写入 " .. tempPath .. "：" .. tostring(openError), 0) end
  local streamed, streamError = pcall(function()
    for chunk in response do
      local written, writeError = output:write(chunk)
      if not written then error(writeError or "unknown write error", 0) end
    end
    finishOutput(output, tempPath)
    output = nil
  end)

  if output then pcall(function() output:close() end) end
  if not streamed then
    pcall(filesystem.remove, tempPath)
    error("读取 " .. relativePath .. " 失败：" .. tostring(streamError), 0)
  end
  if not filesystem.exists(tempPath) or filesystem.size(tempPath) <= 0 then
    pcall(filesystem.remove, tempPath)
    error(relativePath .. " 下载结果为空", 0)
  end
  local renamed, renameError = filesystem.rename(tempPath, targetPath)
  if not renamed then
    pcall(filesystem.remove, tempPath)
    error("无法暂存 " .. relativePath .. "：" .. tostring(renameError), 0)
  end
end

local function readAll(path)
  local input, reason = io.open(path, "rb")
  if not input then error("无法读取 " .. path .. "：" .. tostring(reason), 0) end
  local content, readError = input:read("*a")
  input:close()
  if content == nil then error("读取 " .. path .. " 失败：" .. tostring(readError), 0) end
  return content
end

local function compileLua(path)
  local chunk, reason = load(readAll(path), "@" .. path, "t", _G)
  if not chunk then error(path .. " Lua 语法错误：" .. tostring(reason), 0) end
  return chunk
end

local function validateConfig(path, expectedMode)
  local chunk = compileLua(path)
  local ok, loaded = pcall(chunk)
  if not ok then error(path .. " 执行失败：" .. tostring(loaded), 0) end
  if type(loaded) ~= "table" then error(path .. " 没有返回配置 table", 0) end
  if loaded.mode ~= expectedMode then
    error(path .. " 的 mode 应为 " .. expectedMode .. "，实际为 " .. tostring(loaded.mode), 0)
  end
end

-- v9 preserved user component addresses, but its default 1-2 second polling
-- values also kept the long gap between a completed cycle and prompt return.
-- Migrate only an unmarked v9-style timing block; custom non-default values
-- remain untouched.
local function migratePreservedConfig(path)
  local content = readAll(path)
  if content:find("returnVerifyDelay%s*=") then return false end

  local function replaceDefault(pattern, replacement)
    content = content:gsub(pattern, function(prefix, suffix)
      return prefix .. replacement .. suffix
    end, 1)
  end

  replaceDefault("(\n%s*poll%s*=%s*)1(%s*,)", "0.25")
  replaceDefault("(\n%s*craftPoll%s*=%s*)1(%s*,)", "0.25")
  replaceDefault("(\n%s*cycleSettle%s*=%s*)2(%s*,)", "0.25")

  local indent = content:match("\n([ \t]*)cycleSettle%s*=")
  if not indent then return false end
  local additions = "\n" .. indent .. "interfaceSupplyGrace = 2,"
    .. "\n" .. indent .. "transferYield = 0.05,"
    .. "\n" .. indent .. "returnVerifyDelay = 0.1,"
    .. "\n" .. indent .. "advanceWarningAfter = 30,"
  content = content:gsub("(\n[ \t]*cycleSettle%s*=)", additions .. "%1", 1)
  writeChecked(path, content)
  return true
end

local function validateStage()
  for _, spec in ipairs(files) do
    local path = filesystem.concat(stageRoot, spec.target)
    if not filesystem.exists(path) or filesystem.size(path) <= 0 then
      error("暂存文件缺失或为空：" .. spec.target, 0)
    end
    if spec.configMode then
      validateConfig(path, spec.configMode)
    elseif spec.lua then
      compileLua(path)
    end
  end
end

local function backupCurrentFiles()
  removeTree(rollbackRoot)
  ensureDirectory(rollbackRoot)
  for _, spec in ipairs(files) do
    local currentPath = filesystem.concat(targetRoot, spec.target)
    if filesystem.exists(currentPath) then
      if filesystem.isDirectory(currentPath) then error("目标路径不是文件：" .. currentPath, 0) end
      copyChecked(currentPath, filesystem.concat(rollbackRoot, spec.target))
    end
  end
  writeChecked(rollbackMarker, "FOG Exotic install in progress\n")
end

local function restoreRollback()
  local errors = {}
  for _, spec in ipairs(files) do
    local currentPath = filesystem.concat(targetRoot, spec.target)
    local backupPath = filesystem.concat(rollbackRoot, spec.target)
    local ok, reason = pcall(function()
      if filesystem.exists(currentPath) then removeTree(currentPath) end
      if filesystem.exists(backupPath) then copyChecked(backupPath, currentPath) end
    end)
    if not ok then errors[#errors + 1] = tostring(reason) end
  end
  return errors
end

local function clearTemporaryState()
  removeTree(rollbackRoot)
  removeTree(stageRoot)
end

local function recoverInterruptedInstall()
  if filesystem.exists(rollbackMarker) then
    print("检测到未完成的上次安装，正在恢复旧文件……")
    local errors = restoreRollback()
    if #errors > 0 then error(table.concat(errors, "\n"), 0) end
  end
  clearTemporaryState()
end

local function promoteStage()
  backupCurrentFiles()
  local promoted, promoteError = pcall(function()
    for _, spec in ipairs(files) do
      local stagedPath = filesystem.concat(stageRoot, spec.target)
      local targetPath = filesystem.concat(targetRoot, spec.target)
      if filesystem.exists(targetPath) then removeTree(targetPath) end
      local renamed, reason = filesystem.rename(stagedPath, targetPath)
      if not renamed then error("无法启用 " .. spec.target .. "：" .. tostring(reason), 0) end
    end
  end)

  if not promoted then
    local rollbackErrors = restoreRollback()
    local message = "安装失败，已尝试恢复安装前文件：" .. tostring(promoteError)
    if #rollbackErrors > 0 then message = message .. "\n" .. table.concat(rollbackErrors, "\n") end
    error(message, 0)
  end
  clearTemporaryState()
end

local function stageFiles()
  ensureDirectory(stageRoot)
  for _, spec in ipairs(files) do
    local currentPath = filesystem.concat(targetRoot, spec.target)
    local stagedPath = filesystem.concat(stageRoot, spec.target)
    if spec.preserve and filesystem.exists(currentPath) then
      io.write("保留现有 " .. spec.target .. " … ")
      copyChecked(currentPath, stagedPath)
      if spec.configMode and migratePreservedConfig(stagedPath) then
        print("完成（已升级 v9 默认时序）")
      else
        print("完成")
      end
    elseif spec.generated then
      io.write("生成 " .. spec.target .. " … ")
      writeChecked(stagedPath, spec.generated())
      print("完成")
    else
      io.write("下载 " .. spec.source .. " … ")
      download(spec.source, stagedPath)
      print("完成")
    end
  end
end

local function main()
  ensureDirectory(targetRoot)
  recoverInterruptedInstall()

  if not component.isAvailable("internet") then error("需要 Internet Card", 0) end
  if not component.internet.isHttpEnabled() then error("服务器已禁用 Internet Card 的 HTTP 请求", 0) end

  print("安装全新 FOG 奇异模块自动化 " .. releaseTag .. " 到：" .. targetRoot)
  stageFiles()
  validateStage()
  promoteStage()

  print("")
  print("安装完成。旧 v8 模块不会再被 quark / magmatter 入口调用。")
  print("首次使用请编辑：")
  print("  edit " .. filesystem.concat(targetRoot, "fog_quark.cfg"))
  print("  edit " .. filesystem.concat(targetRoot, "fog_magmatter.cfg"))
  print("运行：")
  print("  quark")
  print("  magmatter")
  print("升级前若曾残留铁/铜等离子体，请先手动从缓存输入仓返网一次。")
  print("新版会从请求源头忽略铁/铜假输入，不会自动搬运旧残留。")
  print("旧 exotic_* 文件不会自动删除；确认新版稳定后可自行清理。")
end

local ok, reason = pcall(main)
if not ok then
  io.stderr:write("安装失败：" .. tostring(reason) .. "\n")
  os.exit(1)
end
