-- Compatibility entry point generated by the release installer for /home.
local program, reason = loadfile("/home/fog_exotic.lua")
if not program then error("无法载入新版 FOG 自动化：" .. tostring(reason), 0) end
return program("/home/fog_magmatter.cfg")
